### ISSUE TITLE
Document is not Defined Error

### ISSUE THREAD

**Issue by maxcado** [Ayms/bitcoin-transactions#36]
-I am trying to use this tool but cannot get past a document is not defined error with nodejs. Cannot create a wallet or build a transaction. When I do node tx.js <crypto-symbol> createwallet <my 64 char secret> <number of addr> <path> I get:

/home/user/tx/bitcoin-transactions-Ayms/tx.js:33
                if (document===undefined)  {

ReferenceError: document is not defined
    at start (/home/user/tx/bitcoin-transactions-Ayms/tx.js:33:3)
   at Object.<anonymous> (/home/user/tx/bitcoin-transactions-Ayms/tx.js:133:4)
   at Module._compile (module.js:635:30)
   at Object.Module._extensions..js (module.js:646:10)
  at Module.load (module.js:554:32)
  at tryModuleLoad (module.js:497:12)
 at Function.Module._load (module.js:489:3)
  at Function.Module.runMain (module.js:676:10)
  at startup (bootstrap_node.js:187:16)
  at bootstrap_node.js:608:3

What should I do?

**Comment by Ayms** [comment]
What nodejs version are you using?

I will look at it, in the meantime you can do ``if (typeof document==='undefined')`` instead of ``if (document===undefined)``

**Comment by Ayms** [comment]
Corrected https://github.com/Ayms/bitcoin-transactions/commit/7aebfc388f0795387a4031edad1289179798637c
